"""Schema definitions for `marketprice.messages.bch` namespace. Generated by avro2py v.0.0.1."""
import datetime
from typing import NamedTuple


class ProductTrigger(NamedTuple):
    """
    BCH Product for Demand Forecast processing:
    MpDataType(mprice/bch/x/demand-forecast/product-trigger)
    """

    channel: str
    sellerId: str
    marketplaceId: str
    sku: str


class ProductDemandEstimate(NamedTuple):
    """
    BCH Demand Forecast response record:
    MpDataType(mprice/bch/x/demand-forecast/deciles)
    """

    channel: str
    sellerId: str
    marketplaceId: str
    sku: str
    forecastDate: datetime.date
    requestedAt: datetime.date
    percentile: str
    estimate: int
