"""Schema definitions for `marketprice.messages.cogs` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
from typing import NamedTuple


class NileProductCogsEvent(NamedTuple):
    """
    MPrice-published COGS Event for an Nile product:
    mprice/cogs/v0/nile-product/event
    """

    sellerId: str
    marketplaceId: str
    sku: str
    cost: "NileProductCogsEvent.Money"
    occurredAt: datetime.datetime
    initiatedBy: str
    effectiveOn: datetime.datetime
    _original_schema = (
        '{"type": "record", "name": "NileProductCogsEvent", "namespace":'
        ' "marketprice.messages.cogs", "doc": "MPrice-published COGS Event for an Nile'
        ' product: mprice/cogs/v0/nile-product/event", "fields": [{"name": "sellerId",'
        ' "type": "string"}, {"name": "marketplaceId", "type": "string"}, {"name":'
        ' "sku", "type": "string"}, {"name": "cost", "type": {"type": "record", "name":'
        ' "Money", "namespace": "marketprice.messages.cogs.NileProductCogsEvent",'
        ' "doc": "Money: decimal(21,2) amount and currency code", "fields": [{"name":'
        ' "amount", "type": {"type": "bytes", "logicalType": "decimal", "precision":'
        ' 21, "scale": 2}}, {"name": "currency", "type": "string"}]}}, {"name":'
        ' "occurredAt", "type": {"type": "long", "logicalType": "timestamp-millis"}},'
        ' {"name": "initiatedBy", "type": "string"}, {"name": "effectiveOn", "type":'
        ' {"type": "long", "logicalType": "timestamp-millis"}}]}'
    )

    class Money(NamedTuple):
        """
        Money: decimal(21,2) amount and currency code
        """

        amount: decimal.Decimal
        currency: str
        _original_schema = (
            '{"type": "record", "name": "Money", "namespace":'
            ' "marketprice.messages.cogs.NileProductCogsEvent", "doc": "Money:'
            ' decimal(21,2) amount and currency code", "fields": [{"name": "amount",'
            ' "type": {"type": "bytes", "logicalType": "decimal", "precision": 21,'
            ' "scale": 2}}, {"name": "currency", "type": "string"}]}'
        )
