"""Schema definitions for `marketprice.messages.cogs` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
from typing import NamedTuple


class NileProductCogsEvent(NamedTuple):
    """
    MPrice-published COGS Event for an Nile product:
    mprice/cogs/v0/nile-product/event
    """

    sellerId: str
    marketplaceId: str
    sku: str
    cost: "NileProductCogsEvent.Money"
    occurredAt: datetime.datetime
    initiatedBy: str
    effectiveOn: datetime.datetime

    class Money(NamedTuple):
        """
        Money: decimal(21,2) amount and currency code
        """

        amount: decimal.Decimal
        currency: str
