"""Schema definitions for `marketprice.messages.example` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
import enum
import uuid
from typing import Dict, NamedTuple, Optional, Union


class ExampleAvroModel(NamedTuple):
    """
    Example Avro Model
    """

    id: uuid.UUID
    encryptedData: str
    timestamp: datetime.datetime
    date: datetime.date
    maybeInt: Optional[int]
    decimal: decimal.Decimal
    maybeDecimal: Optional[decimal.Decimal]
    stringMap: Dict[str, str]
    sampleEnum: "ExampleAvroModel.Cheese"
    sampleUnion: Union[
        "ExampleAvroModel.RecordWithInt", "ExampleAvroModel.RecordWithString"
    ]
    sampleInner: "ExampleAvroModel.ExampleInnerModel"

    class ExampleInnerModel(NamedTuple):
        """
        Example Inner Model
        """

        foo: int
        bar: str

    class RecordWithString(NamedTuple):
        id: uuid.UUID
        value: str

    class RecordWithInt(NamedTuple):
        id: uuid.UUID
        value: int

    @enum.unique
    class Cheese(enum.Enum):
        """
        Example enum
        """

        CHEDDAR = "cheddar"
        HAVARTI = "havarti"
        WENSLEYDALE = "wensleydale"


class SimpleExampleMessageStringData(NamedTuple):
    """
    Simple example message format with string data, for use in examples and testing
    """

    id: uuid.UUID
    name: str
    data: str
    timestamp: datetime.datetime


class SimpleExampleDecimalMessage(NamedTuple):
    """
    Simple example message format with decimals, for use in examples and testing
    """

    id: uuid.UUID
    name: str
    decimal21P2S: decimal.Decimal
    decimal21P6S: decimal.Decimal
    timestamp: datetime.datetime


class SimpleExampleMessage(NamedTuple):
    """
    Simple example message format, for use in examples and testing
    """

    id: uuid.UUID
    name: str
    dataMap: Dict[str, str]
    timestamp: datetime.datetime


class ExampleModelWithMpContentType(NamedTuple):
    """
    Simple example model for testing MpContentType (not used outside of tests)
    """

    id: uuid.UUID
    name: str
    contentType: str
    separateMpDataType: str
    separateMpContentFormat: str
    timestamp: datetime.datetime
