"""Schema definitions for `marketprice.messages.shark.keys` namespace. Generated by avro2py v.0.0.1."""
import uuid
from typing import NamedTuple


class IntKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of an Integer
    """

    id: int


class UuidKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a UUID
    """

    id: uuid.UUID


class StringKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a String
    """

    id: str


class LongKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a Long
    """

    id: int
