"""Schema definitions for `marketprice.messages.neo.wallyworld` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
import enum
import uuid
from typing import NamedTuple, Optional


class AdItemUpdateResponse(NamedTuple):
    """
    Response for an AdItemUpdateRequest message:
    wallyworld-sponsored-products-api/v1/response-update/ad-item
    """

    code: "AdItemUpdateResponse.ResponseCode"
    errorDetails: Optional[str]
    advertiserId: int
    bid: decimal.Decimal
    submissionId: uuid.UUID
    requestedAt: datetime.datetime
    receivedAt: datetime.datetime

    @enum.unique
    class ResponseCode(enum.Enum):
        """
        code returned by Wallyworld API
        """

        FAILURE = "failure"
        SUCCESS = "success"


class KeywordUpdateResponse(NamedTuple):
    """
    Response for a KeywordUpdateRequest message:
    wallyworld-sponsored-products-api/v1/response-update/keyword
    """

    code: "KeywordUpdateResponse.ResponseCode"
    errorDetails: Optional[str]
    advertiserId: int
    bid: decimal.Decimal
    submissionId: uuid.UUID
    requestedAt: datetime.datetime
    receivedAt: datetime.datetime

    @enum.unique
    class ResponseCode(enum.Enum):
        """
        code returned by Wallyworld API
        """

        FAILURE = "failure"
        SUCCESS = "success"


class AdItemUpdateRequest(NamedTuple):
    """
    AdItem update request:
    wallyworld-sponsored-products-api/v1/request-update/ad-item
    """

    advertiserId: int
    campaignId: int
    adGroupId: int
    itemId: str
    bid: decimal.Decimal
    status: str
    submissionId: uuid.UUID
    publishedAt: datetime.datetime
    expiresAt: datetime.datetime


class KeywordUpdateRequest(NamedTuple):
    """
    Keyword update request:
    wallyworld-sponsored-products-api/v1/request-update/keyword
    """

    keywordId: int
    bid: decimal.Decimal
    status: str
    advertiserId: int
    submissionId: uuid.UUID
    publishedAt: datetime.datetime
    expiresAt: datetime.datetime
