"""Schema definitions for `marketprice.pubsub` namespace. Generated by avro2py v.0.0.4."""
from typing import Dict, NamedTuple


class S3FileDescriptor(NamedTuple):
    bucket: str
    key: str
    contentType: str
    contentEncoding: str
    metadata: Dict[str, str]
    _original_schema = (
        '{"type": "record", "name": "S3FileDescriptor", "namespace":'
        ' "marketprice.pubsub", "fields": [{"name": "bucket", "type": "string"},'
        ' {"name": "key", "type": "string"}, {"name": "contentType", "type": "string"},'
        ' {"name": "contentEncoding", "type": "string"}, {"name": "metadata", "type":'
        ' {"type": "map", "values": "string"}}]}'
    )
