"""Schema definitions for `marketprice.messages.historical.replay` namespace. Generated by avro2py v.0.0.1."""
import datetime
from ...pubsub import S3FileDescriptor
from typing import Dict, NamedTuple


class S3DataAvailable(NamedTuple):
    """
    Represents a DataAvailable event with data stored in S3 (inline bytes are not
    supported); otherwise comparable to DataAvailable.
    """

    ownerId: str
    s3FileDescriptor: "S3FileDescriptor"
    mpContentType: str
    requestedAt: datetime.datetime
    receivedAt: datetime.datetime
    requestMetadata: Dict[str, str]
    responseMetadata: Dict[str, str]
