"""Schema definitions for `marketprice.messages.nile.mws` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
from typing import Dict, List, NamedTuple, Optional


class FbaProductFeeEstimate(NamedTuple):
    """
    Mws Fba Product Fee estimate:
    MpDataType(nile-mws-api/2009-01-01/parsed/fba-estimated-fees)
    """

    sellerId: str
    marketplaceId: str
    sku: str
    currency: str
    priceToEstimateAt: decimal.Decimal
    maybeEstimatedReferralFee: Optional[decimal.Decimal]
    maybeEstimatedVariableClosingFee: Optional[decimal.Decimal]
    maybeEstimatedFulfillmentFee: Optional[decimal.Decimal]
    requestedAt: datetime.datetime
    receivedAt: datetime.datetime


class GetMatchingProductForId(NamedTuple):
    """
    GetMatchingProductForId Record:
    nile-mws-api/2009-01-01/parsed/get-matching-product-for-id
    """

    nsin: str
    marketplaceId: str
    parent: Optional[str]
    children: List[str]
    image: Optional["GetMatchingProductForId.ImageData"]
    salesRank: Dict[str, int]
    requestedAt: datetime.datetime
    receivedAt: datetime.datetime
    title: Optional[str]

    class ImageData(NamedTuple):
        url: str
        heightPx: int
        widthPx: int
