"""Schema definitions for `marketprice.messages.events` namespace. Generated by avro2py v.0.0.4."""
import uuid
from typing import NamedTuple


class EventMetadata(NamedTuple):
    """
    Metadata to be associated with every published event
    """

    id: uuid.UUID
    _original_schema = (
        '{"type": "record", "namespace": "marketprice.messages.events", "name":'
        ' "EventMetadata", "doc": "Metadata to be associated with every published'
        ' event", "fields": [{"name": "id", "doc": "Unique identifier for this specific'
        ' event", "type": {"type": "string", "logicalType": "uuid"}}]}'
    )
