"""Schema definitions for `marketprice.messages.events.advertising` namespace. Generated by avro2py v.0.1.0."""
import uuid
from . import EventMetadata
from typing import NamedTuple


class AdConnected(NamedTuple):
    """
    AdConnected
    """

    metadata: "EventMetadata"
    connection_id: uuid.UUID
    _schema = (
        '{"type": "record", "namespace": "marketprice.messages.events.advertising",'
        ' "name": "AdConnected", "doc": "AdConnected", "fields": [{"name": "metadata",'
        ' "type": {"type": "record", "namespace": "marketprice.messages.events",'
        ' "name": "EventMetadata", "doc": "Metadata to be associated with every'
        ' published event", "fields": [{"name": "id", "doc": "Unique identifier for'
        ' this specific event", "type": {"type": "string", "logicalType": "uuid"}}]}},'
        ' {"name": "connection_id", "type": {"type": "string", "logicalType": "uuid"},'
        ' "doc": "ID generated by Channel integration for successful connection."}]}'
    )
