"""Schema definitions for `marketprice.messages.wallyworld.bidder` namespace. Generated by avro2py v.0.0.1."""
import datetime
import decimal
from typing import NamedTuple


class WallyworldKeyword(NamedTuple):
    """
    Wallyworld Keyword Snapshot for bidder:
    wallyworld-sponsored-products-api/entity/v1/parsed-bidder/keyword
    """

    advertiserId: int
    campaignId: int
    adGroupId: int
    keywordId: int
    state: str
    matchType: str
    bid: decimal.Decimal
    requestedAt: datetime.datetime


class WallyworldCampaign(NamedTuple):
    """
    Wallyworld Campaign Snapshot for bidder:
    wallyworld-sponsored-products-api/entity/v1/parsed-bidder/campaign
    """

    advertiserId: int
    campaignId: int
    targetingType: str
    state: str
    requestedAt: datetime.datetime


class WallyworldKeywordReport(NamedTuple):
    """
    Wallyworld Keyword Report for bidder:
    wallyworld-sponsored-products-api/reports/v1/parsed-bidder/keyword
    """

    advertiserId: int
    keywordId: int
    searchTerm: str
    impressions: int
    clicks: int
    unitsOrdered: int
    cost: decimal.Decimal
    sales: decimal.Decimal
    date: datetime.date
    requestedAt: datetime.datetime


class WallyworldAdItemReport(NamedTuple):
    """
    Wallyworld Ad Item Report for bidder:
    wallyworld-sponsored-products-api/reports/v1/parsed-bidder/ad-item
    """

    advertiserId: int
    adGroupId: int
    itemId: str
    date: datetime.date
    cost: decimal.Decimal
    sales: decimal.Decimal
    impressions: int
    clicks: int
    unitsOrdered: int
    requestedAt: datetime.datetime


class WallyworldAdGroupReport(NamedTuple):
    """
    Wallyworld Ad Group Report for bidder:
    wallyworld-sponsored-products-api/reports/v1/parsed-bidder/ad-group
    """

    advertiserId: int
    campaignId: int
    adGroupId: int
    date: datetime.date
    cost: decimal.Decimal
    sales: decimal.Decimal
    impressions: int
    clicks: int
    unitsOrdered: int
    requestedAt: datetime.datetime


class WallyworldAdGroup(NamedTuple):
    """
    Wallyworld Ad Group Snapshot for bidder:
    wallyworld-sponsored-products-api/entity/v1/parsed-bidder/ad-group
    """

    advertiserId: int
    campaignId: int
    adGroupId: int
    state: str
    requestedAt: datetime.datetime


class WallyworldAdItem(NamedTuple):
    """
    Wallyworld Ad Item Snapshot for bidder:
    wallyworld-sponsored-products-api/entity/v1/parsed-bidder/ad-item
    """

    advertiserId: int
    campaignId: int
    adGroupId: int
    adItemId: int
    itemId: str
    state: str
    bid: decimal.Decimal
    requestedAt: datetime.datetime
