"""Schema definitions for `marketprice.messages.shark.keys` namespace. Generated by avro2py v.0.0.6."""
import uuid
from typing import NamedTuple


class IntKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of an Integer
    """

    id: int
    _original_schema = (
        '{"type": "record", "name": "IntKey", "namespace":'
        ' "marketprice.messages.shark.keys", "doc": "Model for a Kafka key consisting'
        ' solely of an Integer", "fields": [{"name": "id", "type": "int"}]}'
    )


class UuidKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a UUID
    """

    id: uuid.UUID
    _original_schema = (
        '{"type": "record", "name": "UuidKey", "namespace":'
        ' "marketprice.messages.shark.keys", "doc": "Model for a Kafka key consisting'
        ' solely of a UUID", "fields": [{"name": "id", "type": {"type": "string",'
        ' "logicalType": "uuid"}}]}'
    )


class StringKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a String
    """

    id: str
    _original_schema = (
        '{"type": "record", "name": "StringKey", "namespace":'
        ' "marketprice.messages.shark.keys", "doc": "Model for a Kafka key consisting'
        ' solely of a String", "fields": [{"name": "id", "type": "string"}]}'
    )


class LongKey(NamedTuple):
    """
    Model for a Kafka key consisting solely of a Long
    """

    id: int
    _original_schema = (
        '{"type": "record", "name": "LongKey", "namespace":'
        ' "marketprice.messages.shark.keys", "doc": "Model for a Kafka key consisting'
        ' solely of a Long", "fields": [{"name": "id", "type": "long"}]}'
    )
