"""Schema definitions for `marketprice.messages.wallyworld.marketplace.v3` namespace. Generated by avro2py v.0.0.6."""
import datetime
import uuid
from typing import NamedTuple


class Credentials(NamedTuple):
    """
    Wallyworld Marketplace API Credentials:
    wallyworld-marketplace-api/v3/credentials
    """

    mpAccountId: uuid.UUID
    clientId: str
    clientSecret: str
    receivedAt: datetime.datetime
    submissionId: uuid.UUID
    publishedAt: datetime.datetime
    _original_schema = (
        '{"type": "record", "name": "Credentials", "namespace":'
        ' "marketprice.messages.wallyworld.marketplace.v3", "doc": "Wallyworld'
        ' Marketplace API Credentials: wallyworld-marketplace-api/v3/credentials",'
        ' "fields": [{"name": "mpAccountId", "type": {"type": "string", "logicalType":'
        ' "uuid"}}, {"name": "clientId", "type": "string"}, {"name": "clientSecret",'
        ' "type": "string"}, {"name": "receivedAt", "type": {"type": "long",'
        ' "logicalType": "timestamp-millis"}}, {"name": "submissionId", "type":'
        ' {"type": "string", "logicalType": "uuid"}}, {"name": "publishedAt", "type":'
        ' {"type": "long", "logicalType": "timestamp-millis"}}]}'
    )


class Response(NamedTuple):
    """
    Wallyworld Marketplace API Credentials:
    wallyworld-marketplace-api/v3/credentials/response
    """

    mpAccountId: uuid.UUID
    submissionId: uuid.UUID
    status: str
    publishedAt: datetime.datetime
    _original_schema = (
        '{"type": "record", "name": "Response", "namespace":'
        ' "marketprice.messages.wallyworld.marketplace.v3", "doc": "Wallyworld'
        " Marketplace API Credentials:"
        ' wallyworld-marketplace-api/v3/credentials/response", "fields": [{"name":'
        ' "mpAccountId", "type": {"type": "string", "logicalType": "uuid"}}, {"name":'
        ' "submissionId", "type": {"type": "string", "logicalType": "uuid"}}, {"name":'
        ' "status", "type": "string"}, {"name": "publishedAt", "type": {"type": "long",'
        ' "logicalType": "timestamp-millis"}}]}'
    )
