"""Schema definitions for `marketprice.pubsub` namespace. Generated by avro2py v.0.0.1."""
from typing import Dict, NamedTuple


class S3FileDescriptor(NamedTuple):
    bucket: str
    key: str
    contentType: str
    contentEncoding: str
    metadata: Dict[str, str]
