"""Schema definitions for `marketprice.messages.wallyworld.marketplace.v3` namespace. Generated by avro2py v.0.0.1."""
import datetime
import uuid
from typing import NamedTuple


class Credentials(NamedTuple):
    """
    Wallyworld Marketplace API Credentials:
    wallyworld-marketplace-api/v3/credentials
    """

    mpAccountId: uuid.UUID
    clientId: str
    clientSecret: str
    receivedAt: datetime.datetime
    submissionId: uuid.UUID
    publishedAt: datetime.datetime


class Response(NamedTuple):
    """
    Wallyworld Marketplace API Credentials:
    wallyworld-marketplace-api/v3/credentials/response
    """

    mpAccountId: uuid.UUID
    submissionId: uuid.UUID
    status: str
    publishedAt: datetime.datetime
